function [ys_, params, info] = steadystate(ys_, exo_, params)
% Steady state generated by Dynare preprocessor
    info = 0;
    ys_(13)=1;
    ys_(12)=1;
    ys_(9)=1;
    ys_(3)=1;
    ys_(7)=1;
    ys_(2)=(1-params(2))/params(2);
    ys_(6)=(params(7)-1)/params(7);
    ys_(8)=ys_(6);
    ys_(1)=(ys_(8)/params(4))^(1/(params(6)+params(1)));
    ys_(5)=ys_(1);
    ys_(10)=ys_(6)*ys_(1)^(1-params(1))/(1-params(2)*params(8));
    ys_(11)=params(7)*ys_(10)/(params(7)-1);
    ys_(4)=((1-params(2))/params(3))^(1/params(5))*ys_(1)^(params(1)/params(5));
    % Auxiliary equations
end
